# Generated by Django 6.0.3 on 2026-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('client', models.CharField(blank=True, default='', max_length=200, verbose_name='客户')),
                ('supplier', models.CharField(blank=True, default='', max_length=200, verbose_name='供应商')),
                ('status', models.CharField(choices=[('preparing', '准备中'), ('construction', '建设中'), ('completed', '已完成'), ('acceptance', '验收中'), ('finished', '已结束'), ('suspended', '已暂停')], default='preparing', max_length=20, verbose_name='项目状态')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预算金额')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目管理',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
