# Generated by Django 6.0.3 on 2026-03-28 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_supplier_alter_client_options'),
        ('projects', '0004_alter_project_client_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.supplier', verbose_name='供应商'),
        ),
        migrations.CreateModel(
            name='SignInQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='二维码名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='二维码Code')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='失效时间')),
                ('location_name', models.CharField(blank=True, default='', max_length=500, verbose_name='签到地点名称')),
                ('latitude', models.CharField(blank=True, default='', max_length=50, verbose_name='纬度')),
                ('longitude', models.CharField(blank=True, default='', max_length=50, verbose_name='经度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signin_qrcodes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signin_qrcodes', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '签到二维码',
                'verbose_name_plural': '签到二维码',
                'db_table': 'projects_signin_qrcode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, default='', max_length=100, verbose_name='签到人姓名')),
                ('person_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='签到人电话')),
                ('person_company', models.CharField(blank=True, default='', max_length=200, verbose_name='单位/公司')),
                ('sign_type', models.CharField(choices=[('checkin', '签到'), ('checkout', '签退')], default='checkin', max_length=20, verbose_name='签到类型')),
                ('sign_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('location', models.CharField(blank=True, default='', max_length=500, verbose_name='签到地点')),
                ('latitude', models.CharField(blank=True, default='', max_length=50, verbose_name='纬度')),
                ('longitude', models.CharField(blank=True, default='', max_length=50, verbose_name='经度')),
                ('qrcode_id', models.CharField(blank=True, default='', max_length=100, verbose_name='二维码ID')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signin_records', to='projects.project', verbose_name='关联项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signin_records', to=settings.AUTH_USER_MODEL, verbose_name='签到人')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'db_table': 'projects_signin_record',
                'ordering': ['-sign_time'],
            },
        ),
    ]
