# Generated by Django-3.2.3 on 2026-03-30
# P0修复: 合并冗余表 (equipment/material/invoices)
# 
# 合并逻辑说明:
# 1. inventory_equipment_new → inventory_equipment
# 2. inventory_material_new → inventory_material (或 materials)
# 3. finance_invoices_new → invoices
#
# 执行前请先备份数据!

from django.db import migrations, models


def migrate_equipment_forward(apps, schema_editor):
    """equipment_new 数据合并到 equipment"""
    EquipmentNew = apps.get_model('inventory', 'EquipmentNew')
    Equipment = apps.get_model('inventory', 'Equipment')
    
    for item in EquipmentNew.objects.all():
        Equipment.objects.create(
            name=item.name,
            code=f"NEW-{item.id}",  # 避免code冲突
            specification=item.specification,
            status=item.status,
            purchase_date=None,
            purchase_price=0,
            current_assignee=None,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )
    # 合并后可清空 EquipmentNew
    # EquipmentNew.objects.all().delete()


def migrate_material_forward(apps, schema_editor):
    """inventory_material_new 数据合并到 materials"""
    MaterialNew = apps.get_model('inventory', 'MaterialNew')
    Material = apps.get_model('inventory', 'Material')
    
    for item in MaterialNew.objects.all():
        Material.objects.create(
            name=item.name,
            code=f"NEW-{item.id}",
            unit=item.unit,
            specification=item.specification,
            stock_quantity=item.stock,
            min_stock=item.alert_threshold,
            unit_price=0,
            category_id=1,  # 默认分类，需确认
            created_at=item.created_at,
            updated_at=item.updated_at,
        )


def migrate_invoice_forward(apps, schema_editor):
    """finance_invoices_new 数据合并到 invoices"""
    InvoiceNew = apps.get_model('finance', 'InvoiceNew')
    Invoice = apps.get_model('finance', 'Invoice')
    
    for item in InvoiceNew.objects.all():
        # 先创建 financial_record
        FinancialRecord = apps.get_model('finance', 'FinancialRecord')
        record = FinancialRecord.objects.create(
            type='income' if item.type == 'income' else 'expense',
            amount=item.amount,
            category='invoice',
            description=f"发票: {item.invoice_no}",
            status='pending',
            is_locked=False,
            record_date=item.issue_date or item.created_at.date(),
            operator_id=1,  # 需确认默认操作人
        )
        Invoice.objects.create(
            invoice_number=item.invoice_no,
            status=item.status,
            invoice_date=item.issue_date,
            amount=item.amount,
            verified_at=None,
            record=record,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )


def reverse_migration(apps, schema_editor):
    """回滚: 不自动恢复数据，仅记录"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipmentio_project_alter_materialio_project'),
        ('finance', '0005_expense_operator_expense_updated_at_income_operator_and_more'),
        # 确保依赖上面的软删除迁移
    ]

    operations = [
        # === 1. 合并设备表 ===
        migrations.RunPython(
            code=migrate_equipment_forward,
            reverse_code=reverse_migration,
        ),
        # 合并后可安全删除 EquipmentNew:
        # migrations.DeleteModel(name='EquipmentNew'),
        
        # === 2. 合并物料表 ===
        migrations.RunPython(
            code=migrate_material_forward,
            reverse_code=reverse_migration,
        ),
        # 合并后可安全删除 MaterialNew:
        # migrations.DeleteModel(name='MaterialNew'),
        
        # === 3. 合并发票表 ===
        migrations.RunPython(
            code=migrate_invoice_forward,
            reverse_code=reverse_migration,
        ),
        # 合并后可安全删除 InvoiceNew:
        # migrations.DeleteModel(name='InvoiceNew'),
        
        # === 4. 清理冗余外键后的表 ===
        # 以下为建议清理项，实际执行前需确认业务影响
        
        # 删除 equipment_old, material_old, invoices_old (如果存在)
        # migrations.DeleteModel(name='EquipmentOld'),
        # migrations.DeleteModel(name='MaterialOld'),
        # migrations.DeleteModel(name='InvoiceOld'),
    ]


# ============================================================
# 备选方案: 如果不想立即合并，可使用视图抽象层
# ============================================================
"""
# 创建视图: v_all_equipment (设备统一视图)
CREATE VIEW v_all_equipment AS
SELECT 
    id, name, code, specification, status,
    purchase_date, purchase_price, current_assignee_id,
    created_at, updated_at,
    'new' AS source
FROM inventory_equipment_new
UNION ALL
SELECT 
    id, name, code, specification, status,
    purchase_date, purchase_price, current_assignee_id,
    created_at, updated_at,
    'old' AS source
FROM inventory_equipment;
"""

print("""
================================================================================
⚠️  执行前必读:
================================================================================
1. 【备份】执行前必须备份数据库:
   pg_dump engineering_db > backup_before_merge_$(date +%Y%m%d).sql

2. 【数据核对】运行以下SQL核对数据量:
   SELECT COUNT(*) FROM inventory_equipment_new;
   SELECT COUNT(*) FROM inventory_material_new;
   SELECT COUNT(*) FROM finance_invoices_new;

3. 【业务确认】合并会修改 code 字段前缀 (NEW-)，需确认业务影响

4. 【分步执行】建议分三次执行，每次一个模块

5. 【回滚方案】保留备份即可回滚
================================================================================
""")
