# Generated by Django 6.0.3 on 2026-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='收支分类')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('reconciled', '已对账'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('is_locked', models.BooleanField(default=False, verbose_name='是否锁定')),
                ('record_date', models.DateField(verbose_name='发生日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '财务记录',
                'verbose_name_plural': '财务管理',
                'db_table': 'financial_records',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='发票号')),
                ('status', models.CharField(choices=[('pending', '待开票'), ('issued', '已开票'), ('verified', '已核销'), ('void', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='开票日期')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='发票金额')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票管理',
                'db_table': 'invoices',
            },
        ),
    ]
