# Generated by Django 6.0.3 on 2026-03-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_supplier_alter_client_options'),
        ('finance', '0002_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-record_date'], 'verbose_name': '财务记录（兼容）', 'verbose_name_plural': '财务管理（兼容）'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '发票（兼容）', 'verbose_name_plural': '发票管理（兼容）'},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('date', models.DateField(verbose_name='日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('attachment', models.CharField(blank=True, default='', max_length=500, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.project', verbose_name='关联项目')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='crm.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出管理',
                'db_table': 'finance_expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('date', models.DateField(verbose_name='日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('attachment', models.CharField(blank=True, default='', max_length=500, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='crm.customer', verbose_name='客户')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '收入',
                'verbose_name_plural': '收入管理',
                'db_table': 'finance_incomes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='发票号')),
                ('type', models.CharField(choices=[('income', '收入发票'), ('expense', '支出发票')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('status', models.CharField(choices=[('issued', '已开票'), ('paid', '已支付'), ('cancelled', '已作废')], default='issued', max_length=20, verbose_name='状态')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='开票日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_new', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '发票（新）',
                'verbose_name_plural': '发票管理（新）',
                'db_table': 'finance_invoices_new',
                'ordering': ['-created_at'],
            },
        ),
    ]
