# Generated by Django 6.0.3 on 2026-03-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_financialrecord_options_alter_invoice_options_and_more'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicenew',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_new', to='projects.project', verbose_name='关联项目'),
        ),
    ]
