# Generated by Django 6.0.3 on 2026-04-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_operator_expense_updated_at_income_operator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('bank_card', models.CharField(blank=True, default='', max_length=30, verbose_name='银行卡号')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='基本工资')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='加班费')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='奖金')),
                ('social_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='社保')),
                ('housing_fund', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='公积金')),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='请假扣款')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='其他扣款')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='个税前工资')),
                ('tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='个税')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='实发工资')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], verbose_name='月份')),
                ('department', models.CharField(blank=True, default='', max_length=50, verbose_name='部门')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='职位')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已批准'), ('paid', '已发放')], default='draft', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wage_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_records', to='finance.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '工资单',
                'verbose_name_plural': '工资管理',
                'db_table': 'finance_wage_records',
                'ordering': ['-year', '-month', 'company__name', 'employee_name'],
                'unique_together': {('company', 'employee_name', 'year', 'month')},
            },
        ),
    ]
