# Generated by Django-3.2.3 on 2026-03-30
# P0修复: 添加软删除字段

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_client_supplier'),
        ('tasks', '0003_add_priority_field'),
        ('crm', '0002_customer_supplier_alter_client_options'),
        ('finance', '0005_expense_operator_expense_updated_at_income_operator_and_more'),
        ('inventory', '0004_alter_equipmentio_project_alter_materialio_project'),
    ]

    operations = [
        # === 软删除字段 ===
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='income',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_deleted',
            field=models.BooleanField(default=False, db_index=True, verbose_name='已删除'),
        ),
        
        # === CHECK约束 ===
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(
                check=models.Q(('progress__gte', 0), ('progress__lte', 100)),
                name='task_progress_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('status__in', ['planning', 'running', 'paused', 'completed', 'cancelled'])
                ),
                name='project_status_valid',
            ),
        ),
    ]
