# Generated by Django 6.0.3 on 2026-03-28 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_add_signin_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('id_card_type', models.CharField(choices=[('id_card', '身份证'), ('passport', '护照')], default='id_card', max_length=20, verbose_name='证件类型')),
                ('work_type', models.CharField(blank=True, choices=[('rebar', '钢筋工'), ('carpenter', '木工'), ('plumber', '水电工'), ('electrician', '电工'), ('painter', '油漆工'), ('general', '杂工'), ('driver', '司机'), ('foreman', '工长')], max_length=20, verbose_name='工种')),
                ('skill_level', models.CharField(choices=[('junior', '初级'), ('intermediate', '中级'), ('senior', '高级')], default='junior', max_length=20, verbose_name='技能等级')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职'), ('suspended', '暂停')], default='active', max_length=20, verbose_name='状态')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入场日期')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='退场日期')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='workers/avatars/', verbose_name='头像')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '施工人员',
                'verbose_name_plural': '施工人员',
                'db_table': 'attendance_workers',
            },
        ),
        migrations.CreateModel(
            name='AttendanceQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(max_length=64, unique=True, verbose_name='二维码唯一ID')),
                ('valid_from', models.DateTimeField(verbose_name='有效期起始')),
                ('valid_until', models.DateTimeField(verbose_name='有效期截止')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_qrcodes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_qrcodes', to='projects.project', verbose_name='关联项目')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_qrcodes', to='gps_attendance.worker', verbose_name='使用人')),
            ],
            options={
                'verbose_name': '签到二维码',
                'verbose_name_plural': '签到二维码',
                'db_table': 'attendance_qr_codes',
            },
        ),
        migrations.CreateModel(
            name='ProjectGPSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='工地中心纬度')),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='工地中心经度')),
                ('radius_meters', models.IntegerField(default=500, verbose_name='允许签到半径（米）')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='GPS校验是否启用')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='工地地址描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gps_settings', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目GPS配置',
                'verbose_name_plural': '项目GPS配置',
                'db_table': 'attendance_project_gps_settings',
            },
        ),
        migrations.CreateModel(
            name='WorkerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班组名称')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_groups', to='gps_attendance.worker', verbose_name='班组长')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_groups', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组',
                'db_table': 'attendance_worker_groups',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='gps_attendance.workergroup', verbose_name='所属班组'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='签到纬度')),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='签到经度')),
                ('check_in_location_valid', models.BooleanField(default=True, verbose_name='签到位置是否有效')),
                ('check_in_distance_meters', models.IntegerField(blank=True, null=True, verbose_name='签到距工地距离')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='签退纬度')),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='签退经度')),
                ('check_out_location_valid', models.BooleanField(default=True, verbose_name='签退位置是否有效')),
                ('check_out_distance_meters', models.IntegerField(blank=True, null=True, verbose_name='签退距工地距离')),
                ('status', models.CharField(choices=[('normal', '正常'), ('late', '迟到'), ('early_leave', '早退'), ('absent', '缺勤')], default='normal', max_length=20, verbose_name='考勤状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='projects.project', verbose_name='签到项目')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='gps_attendance.attendanceqrcode', verbose_name='签到二维码')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='gps_attendance.worker', verbose_name='施工人员')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='gps_attendance.workergroup', verbose_name='班组')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'db_table': 'attendance_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendanceqrcode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_qrcodes', to='gps_attendance.workergroup', verbose_name='班组'),
        ),
    ]
