# Generated by Django 6.0.3 on 2026-03-25 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_supplier_alter_client_options'),
        ('inventory', '0002_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('specification', models.CharField(blank=True, default='', max_length=500, verbose_name='规格型号')),
                ('model', models.CharField(blank=True, default='', max_length=200, verbose_name='设备型号')),
                ('status', models.CharField(choices=[('idle', '闲置'), ('in_use', '使用中'), ('maintenance', '维修中')], default='idle', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='存放地点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备（新）',
                'verbose_name_plural': '设备管理（新）',
                'db_table': 'inventory_equipment_new',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '设备（兼容）', 'verbose_name_plural': '设备管理（兼容）'},
        ),
        migrations.AlterModelOptions(
            name='equipmentlog',
            options={'ordering': ['-created_at'], 'verbose_name': '设备使用记录（兼容）', 'verbose_name_plural': '设备使用记录管理（兼容）'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '物料（兼容）', 'verbose_name_plural': '物料管理（兼容）'},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': '物料分类（兼容）', 'verbose_name_plural': '物料分类管理（兼容）'},
        ),
        migrations.AlterModelOptions(
            name='materialstock',
            options={'ordering': ['-created_at'], 'verbose_name': '库存流水（兼容）', 'verbose_name_plural': '库存流水管理（兼容）'},
        ),
        migrations.CreateModel(
            name='EquipmentIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('borrow', '领用'), ('return', '归还')], max_length=10, verbose_name='类型')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_io_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='关联项目')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_records', to='inventory.equipmentnew', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备出入库',
                'verbose_name_plural': '设备出入库管理',
                'db_table': 'inventory_equipment_io',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物料名称')),
                ('specification', models.CharField(blank=True, default='', max_length=500, verbose_name='规格型号')),
                ('unit', models.CharField(choices=[('pcs', '个'), ('kg', '千克'), ('m', '米'), ('set', '套')], default='pcs', max_length=10, verbose_name='单位')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前库存')),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预警阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_new_records', to='crm.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '物料（新）',
                'verbose_name_plural': '物料管理（新）',
                'db_table': 'inventory_material_new',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10, verbose_name='类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_io_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='关联项目')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_records', to='inventory.materialnew', verbose_name='物料')),
            ],
            options={
                'verbose_name': '物料出入库',
                'verbose_name_plural': '物料出入库管理',
                'db_table': 'inventory_material_io',
                'ordering': ['-created_at'],
            },
        ),
    ]
