# Generated by Django 6.0.3 on 2026-03-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipmentnew_alter_equipment_options_and_more'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentio',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='materialio',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='关联项目'),
        ),
    ]
