# Generated by Django 6.0.3 on 2026-03-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipmentio_project_alter_materialio_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialnew',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价（元）'),
        ),
    ]
