# Generated by Django 6.0.3 on 2026-03-27 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='项目地址')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开工日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='竣工日期')),
                ('status', models.CharField(choices=[('planning', '筹备中'), ('ongoing', '进行中'), ('suspended', '已停工'), ('completed', '已竣工')], default='planning', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目列表',
                'db_table': 'worker_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='身份证号格式不正确（应为18位）', regex='^\\d{17}[\\dXx]$')], verbose_name='身份证号')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='手机号格式不正确', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('work_type', models.CharField(choices=[('rebar', '钢筋工'), ('carpenter', '木工'), ('concrete', '混凝土工'), ('plumber', '水电工'), ('painter', '油漆工'), ('scaffolder', '架子工'), ('laborer', '杂工')], max_length=20, verbose_name='工种')),
                ('skill_level', models.CharField(blank=True, choices=[('junior', '初级'), ('intermediate', '中级'), ('senior', '高级'), ('master', '技师')], max_length=20, verbose_name='技能等级')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职'), ('paused', '暂停')], default='active', max_length=20, verbose_name='状态')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入场日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='退场日期')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=11, verbose_name='紧急联系电话')),
                ('health_cert', models.CharField(blank=True, max_length=50, verbose_name='健康证号')),
                ('safety_cert', models.CharField(blank=True, max_length=50, verbose_name='安全证号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '施工人员',
                'verbose_name_plural': '施工人员列表',
                'db_table': 'workers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班组名称')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='手机号格式不正确', regex='^1[3-9]\\d{9}$')], verbose_name='联系电话')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='workers.worker', verbose_name='班组长')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='workers.project', verbose_name='当前项目')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组列表',
                'db_table': 'worker_groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.workergroup', verbose_name='所属班组'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['name'], name='workers_name_d1fe14_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['id_card'], name='workers_id_card_6a2569_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['phone'], name='workers_phone_7660b8_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['status'], name='workers_status_36a790_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['work_type'], name='workers_work_ty_84794e_idx'),
        ),
    ]
