# Generated by Django 6.0.3 on 2026-03-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('contact_person', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('blacklisted', '已拉黑')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='合同名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('type', models.CharField(choices=[('sale', '销售合同'), ('purchase', '采购合同'), ('service', '服务合同')], default='sale', max_length=20, verbose_name='合同类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='合同金额')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.client', verbose_name='关联客户')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同管理',
                'db_table': 'contracts',
            },
        ),
    ]
