# Generated by Django 6.0.3 on 2026-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('potential', '潜在客户'), ('active', '活跃客户'), ('finished', '已结束')], default='potential', max_length=20, verbose_name='状态')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'db_table': 'crm_customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='供应品类')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商管理',
                'db_table': 'crm_suppliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '客户（兼容）', 'verbose_name_plural': '客户管理（兼容）'},
        ),
    ]
