# Generated by Django 6.0.3 on 2026-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='文件名')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('document', '文档'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('md5', models.CharField(blank=True, default='', max_length=32, verbose_name='MD5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件管理',
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '项目附件',
                'verbose_name_plural': '项目附件',
                'db_table': 'project_attachments',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'db_table': 'task_attachments',
            },
        ),
    ]
