# Generated by Django 6.0.3 on 2026-03-26 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0004_alter_invoicenew_project'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='审批名称')),
                ('flow_type', models.CharField(choices=[('payment', '付款审批'), ('project', '立项审批'), ('change', '变更审批')], max_length=20, verbose_name='审批类型')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approvals', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='finance.expense', verbose_name='关联支出')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '审批流',
                'verbose_name_plural': '审批流',
                'db_table': 'approval_flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_order', models.IntegerField(default=1, verbose_name='审批顺序')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='approvals.approvalflow', verbose_name='所属审批流')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'db_table': 'approval_nodes',
                'ordering': ['node_order'],
            },
        ),
    ]
