# Generated by Django 6.0.3 on 2026-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='直接存储的付款金额（可选，与expense金额可不同）', max_digits=14, null=True, verbose_name='付款金额'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='description',
            field=models.TextField(blank=True, default='', help_text='审批原因或备注', verbose_name='审批说明'),
        ),
    ]
