# Generated by Django 6.0.3 on 2026-03-26 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('info', '通知'), ('warning', '警告'), ('success', '成功'), ('danger', '危险')], default='info', max_length=20, verbose_name='类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='跳转链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知管理',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
